/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface": "#131317",
        "surface-dim": "#131317",
        "surface-bright": "#39393d",
        "surface-container-lowest": "#0e0e12",
        "surface-container-low": "#1b1b1f",
        "surface-container": "#1f1f23",
        "surface-container-high": "#2a292e",
        "surface-container-highest": "#353439",
        "on-surface": "#e5e1e7",
        "on-surface-variant": "#b9cacb",
        "inverse-surface": "#e5e1e7",
        "inverse-on-surface": "#303034",
        "outline": "#849495",
        "outline-variant": "#3a494b",
        "surface-tint": "#00dce6",
        "primary": "#e0fdff",
        "on-primary": "#00373a",
        "primary-container": "#00f2fe",
        "on-primary-container": "#006a70",
        "inverse-primary": "#00696f",
        "secondary": "#e0b6ff",
        "on-secondary": "#4c007d",
        "secondary-container": "#6d11ad",
        "on-secondary-container": "#d7a4ff",
        "tertiary": "#f1f8ff",
        "on-tertiary": "#00354a",
        "tertiary-container": "#b2e1ff",
        "on-tertiary-container": "#00678c",
        "error": "#ffb4ab",
        "on-error": "#690005",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
        "primary-fixed": "#6ff6ff",
        "primary-fixed-dim": "#00dce6",
        "on-primary-fixed": "#002022",
        "on-primary-fixed-variant": "#004f53",
        "secondary-fixed": "#f2daff",
        "secondary-fixed-dim": "#e0b6ff",
        "on-secondary-fixed": "#2e004e",
        "on-secondary-fixed-variant": "#6a0baa",
        "tertiary-fixed": "#c4e7ff",
        "tertiary-fixed-dim": "#7bd0ff",
        "on-tertiary-fixed": "#001e2c",
        "on-tertiary-fixed-variant": "#004c69",
        "background": "#131317",
        "on-background": "#e5e1e7",
        "surface-variant": "#353439",
        "telemetry-cyan": "#00f2fe",
        "telemetry-azure": "#38bdf8",
        "aurora-violet": "#9d4edd",
        "status-warning": "#c86a50",
        "surface-glass": "rgba(255, 255, 255, 0.03)",
        "border-glass": "rgba(255, 255, 255, 0.08)",
        "border-glass-active": "rgba(0, 242, 254, 0.35)",
        "text-dim": "#71717a",
        "text-bright": "#f4f4f5",
      },
      borderRadius: {
        none: "0px",
        sm: "0.25rem",
        DEFAULT: "0.5rem",
        md: "0.625rem",
        lg: "0.75rem",
        xl: "1rem",
        "2xl": "1.25rem",
        "3xl": "1.5rem",
        full: "9999px",
      },
      spacing: {
        "gutter-mobile": "0.75rem",
        "margin-mobile": "1rem",
        "margin": "3rem",
        "gutter": "1.5rem",
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2.5rem",
      },
      fontFamily: {
        headline: ["Geist", "Inter", "sans-serif"],
        body: ["Inter", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
      },
      animation: {
        'pulse-slow': 'pulse 4s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'spin-slow': 'spin 12s linear infinite',
      },
    },
  },
  plugins: [],
}
